#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

# Symlink bin command to /usr/bin
rm -f /usr/bin/cursor
ln -s /usr/share/cursor/cursor /usr/bin/cursor

# make sure chrome-sandbox has right permissions
sudo chmod 4755 /usr/share/cursor/chrome-sandbox
